backend:
  name: git-gateway
  branch: main # Asegúrate de que tu rama en GitHub se llame 'main'

media_folder: "images"
public_folder: "/images"

collections:
  - name: "configuracion_web"
    label: "Contenido de la Web"
    files:
      - label: "Galería Antes y Después"
        name: "galeria"
        file: "data/galeria.json"
        fields:
          - label: "Casos de Éxito (Puedes añadir todos los que quieras)"
            name: "casos"
            widget: "list"
            fields:
              - { label: "Foto Antes", name: "antes", widget: "image" }
              - { label: "Foto Después", name: "despues", widget: "image" }
